apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: abilabi-page-tls
spec:
  secretName: abilabi-page
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: abilabi.page
  dnsNames:
    - abilabi.page
    - www.abilabi.page
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - abilabi.page
          - www.abilabi.page
